name: Autossh
version: 0.7.2
slug: autossh
description: Automatically connect to a ssh server for forwarding ports
url: https://github.com/psallandre/hassio-addons-autossh
arch:
  - armv7
  - amd64
  - aarch64
startup: application
boot: auto
host_network: true
privileged:
  - SYS_ADMIN
apparmor: false
map:
  - share:rw
image: psallandre/hassio-autossh-{arch}
options:
  hostname: ""
  ssh_port: 22
  username: ""
  remote_forwarding:
    - 127.0.0.1:8123:172.17.0.1:8123
  local_forwarding:
    - ""
  other_ssh_options: "-v"
  monitor_port: 0
  gatetime: 30
  init_local_command: ""
  init_remote_command: ""
  retry_interval: 30
  key_name: autossh_rsa_key
  private_key: ""
  share: true
schema:
  hostname: str
  ssh_port: int
  username: str
  remote_forwarding:
    - str
  local_forwarding:
    - str
  other_ssh_options: str
  monitor_port: int
  gatetime: int
  init_local_command: str
  init_remote_command: str
  retry_interval: int
  key_name: str
  private_key: str
  share: bool
